### ISSUE TITLE
Does it support migration from MySQL 4.1

### ISSUE THREAD

**Issue by MichaelDBA** [AnatolyUss/nmig#45]
MySQL 4.1 does not have visible system metadata tables.  That's why I asked.

**Comment by AnatolyUss** [comment]
Hello Michael,
I didn't test it with MySQL prior to 5.6.21 .
Could you tell a little bit more about your migration?
Did it succeed in general?
What issue caused you a trouble, if any?
If such issue took place, then could you send me the `errors-only.log` file (zipped please)?

**Comment by MichaelDBA** [comment]
I am considering tools to use.  So I just want this answer before I start evaulating it.  Can you just tell me if the program relies on querying the system/metadata tables in MySQL?  If it does, then we know it won't work for MySQL pre 5.0.

**Comment by AnatolyUss** [comment]
System/metadata tables are used in order to create foreign keys when appropriate.
If such tables are missing, then the issue will be logged 
and the process of migration will proceed to its next step.
I am closing this issue, because as it currently stands, there is no actual issue.
In case you have more pre-migration questions, please send me an email `anatolyuss@gmail.com`.
