### ISSUE TITLE
Convert MUYSQL BLOB FIELD

### ISSUE THREAD

**Issue by chamilsanjeewa** [AnatolyUss/nmig#52]
In Mysql I have a table column(blob) that keeps php serialized object.
Using  nmig I  migrated that table in ot postgresql and later I found that, I can not  unserialize that column (bytea) using php unserialize( ).

I feel that there is  something not right at converting blog to byeta.

`module.exports = (arrTableColumns, mysqlVersion) => {
    let strRetVal               = '';
    const arrTableColumnsLength = arrTableColumns.length;
    const wkbFunc               = mysqlVersion >= 5.76 ? 'ST_AsWKB' : 'AsWKB';

    for (let i = 0; i < arrTableColumnsLength; ++i) {
        const field = arrTableColumns[i].Field;
        const type  = arrTableColumns[i].Type;

        if (isSpacial(type)) {
            strRetVal += 'HEX(' + wkbFunc + '(`' + field + '`)) AS `' + field + '`,';
        } else if (isBinary(type)) {
            strRetVal += 'HEX(`' + field + '`) AS `' + field + '`,';
        } else if (isBit(type)) {
            strRetVal += 'BIN(`' + field + '`) AS `' + field + '`,';
        } else if (isDateTime(type)) {
            strRetVal += 'IF(`' + field +  '` IN(\'0000-00-00\', \'0000-00-00 00:00:00\'), \'-INFINITY\', CAST(`'
                +  field + '` AS CHAR)) AS `' + field + '`,';
        } else {
            strRetVal += '`' + field + '` AS `' + field + '`,';
        }
    }

    return strRetVal.slice(0, -1);
};`
Its really appreciate your help about this.

**Comment by AnatolyUss** [comment]
Hello Chamil,
Thanks for posting this issue!

In general, blob columns intended to store large binary data, while text
columns intended to store large text.
The serialize function returns a value of type "string", and not of type
"resource".
If MySQL allows you to store a string in a blob column, it doesn't mean
that it is actually a good practice.

Is there any special reason to use blob instead of text to store serialized
objects?
If no, then I suggest to convert your blob column to text prior to the
migration.

-- Sample script:
ALTER TABLE `your_table` CHANGE `your_column` `your_column` TEXT;

Please, let me know if you have any further questions.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-12-19 10:10 GMT+02:00 Chamil Sanjeewa <notifications@github.com>:
