### ISSUE TITLE
Run in cli and upload to npmjs.com

### ISSUE THREAD

**Issue by hendrul** [AnatolyUss/nmig#55]
This tools is one of a kind, I thank you so much for this work!, what is missing is an easier and straight forward install and execution process. I think the steps would be making it a CLI tool and uploading to npmjs.com

**Comment by AnatolyUss** [comment]
Hi,  
Thank you very much for your feedback!  
Could you share with me, what exactly wasn't clear (installation, configuration, etc...) ?   
Thanks again!

**Comment by hendrul** [comment]
Well to improve developer experience it would be a lot easier if a could
```sh
npm install -g nmig
nmig --source postgres://localhost:5432/mydatabase --destination mysql://localhost:3306/mydatabase ...
```
or 
```sh
nmig --config ./config.json
```

**Comment by averrips** [comment]
Yes, thanks so much for this package! I agree that it would definitely be useful to install through NPM. Especially the --config option(s) would be handy.

This would ease collaboration while planning data migrations within teams. Config files could more easily be checked in separately to version control and thus being integrated in code reviews without the need for updating .gitignore (which now only works when everyone uses the same relative install paths).

**Comment by AnatolyUss** [comment]
Hello,
Now, when version 5.3.0 is out, you can move the entire config folder out of Nmig's directory and place it in any location.
As an option, you also can store the Nmig's logs in any location. 
All you need to do is to create the <code>nmig_logs</code> directory.

Please, use following command to start Nmig with custom location of the config:
<code>$ npm start -- --conf-dir='/path/to/nmig_config' --logs-dir='/path/to/nmig_logs'</code>

**Comment by crewsycrews** [comment]
Hey, @AnatolyUss. 
I'm joining to the guys above and thank you for the good package. 
But still, it would be great to have it published on [npm registry](https://docs.npmjs.com/cli/v8/commands/npm-publish) as a stright forward executable so that we don't need to clone whole repo -> install deps -> build app -> run it. In nowadays scenarios CLI tools like `nmig` are installed globally on the system with 1 command `npm install -g <name-of-package>` suggested by @hendrul. 

Step by step guide:
1. Sign up to https://www.npmjs.com/
1. Issue new access token 
1. `npm login`
1. `npm run build`
1. `npm publish`
1. Include npm publish into github releases workflow: https://docs.github.com/en/actions/tutorials/publish-packages/publish-nodejs-packages using previously issued token

All of the steps are needed to be done by you, so that you'll own the package. Anyone can actually do it, but since you're the maintainer of it, all the credits should go to your account and reference you.
