### ISSUE TITLE
boolean to int

### ISSUE THREAD

**Issue by Marzie79** [AnatolyUss/nmig#90]
hello guys.
I think nmig is perfect but I have an issue with it.
boolean type in mysql convert to int type in postgresql and I don't know why this thing happens

**Comment by AnatolyFromPerion** [comment]
Hello Marzie,
As long as I know, in MySQL <code>boolean</code> is an alias of <code>tinyint(1)</code>.
The <code>show full columns from {some_table};</code> queries emit only <code>tinyint(1)</code> for <code>boolean</code> columns, hence <code>nmig</code> creates <code>smallint</code> columns in such cases.

Solution proposal:
Have a look at <code>/nmig/config/data_types_map.json</code> file.
This is a configuration, defining how to map MySQL data types to PostgreSQL.
Find the <code>tinyint</code> definition. (line 33)
If you certain that all the <code>tinyint</code> columns in your database are actually booleans, then change <code>type</code> value to <code> boolean</code> instead of <code>smallint</code>.
Then rerun <code>nmig</code>.

If you discovered this issue after converting your production database, then try to convert these columns to <code>boolean</code>.
Something like this:
<code>alter table table_name alter column column_name type bool using mycol::int::bool;</code>

**Comment by Marzie79** [comment]
**yes**. Your answer is correct. My problem was solved. Thank you so much for your answer.

**Comment by AnatolyFromPerion** [comment]
My pleasure, Marzie.
Thanks for the feedback!
